import { describe, expect, test } from 'bun:test'
import { spawnSync } from 'node:child_process'
import { analyzeFrame, captureFrameScript } from '@/verify/screenshot.ts'
import { frameResult } from '@/verify/report.ts'

/** Build a P6 PPM whose pixels come from `pixel(index)`. */
const ppm = (
    width: number,
    height: number,
    pixel: (i: number) => [number, number, number],
    header?: string
): Buffer => {
    const head = Buffer.from(header ?? `P6\n${width} ${height}\n255\n`, 'ascii')
    const body = Buffer.alloc(width * height * 3)
    for (let i = 0; i < width * height; i++) {
        const [r, g, b] = pixel(i)
        body[i * 3] = r
        body[i * 3 + 1] = g
        body[i * 3 + 2] = b
    }
    return Buffer.concat([head, body])
}

describe('analyzeFrame', () => {
    test('a flat field reports full uniformity — the gray-desktop signature', () => {
        const frame = analyzeFrame(ppm(64, 48, () => [0x3c, 0x3c, 0x3c]))
        expect(frame.width).toBe(64)
        expect(frame.height).toBe(48)
        expect(frame.uniformFraction).toBe(1)
        expect(frame.dominantColor).toBe('#3c3c3c')
    })

    test('a half-and-half frame reports the majority colour and its share', () => {
        const frame = analyzeFrame(
            ppm(10, 10, i => (i < 50 ? [255, 0, 0] : [0, 0, 255]))
        )
        expect(frame.uniformFraction).toBeCloseTo(0.5, 5)
    })

    test('a console with sparse text stays under the blank threshold', () => {
        // ~2% non-background, which is roughly a login prompt.
        const frame = analyzeFrame(
            ppm(100, 100, i => (i % 50 === 0 ? [255, 255, 255] : [0, 0, 0]))
        )
        expect(frame.uniformFraction).toBeLessThan(0.9995)
    })

    test('header comments and extra whitespace are tolerated', () => {
        const frame = analyzeFrame(
            ppm(4, 4, () => [1, 2, 3], 'P6\n# generated by qemu\n4  4\n255\n')
        )
        expect(frame.width).toBe(4)
        expect(frame.dominantColor).toBe('#010203')
    })

    test('rejects formats it cannot honestly measure', () => {
        expect(() => analyzeFrame(Buffer.from('P3\n1 1\n255\n0 0 0'))).toThrow(
            /P6/
        )
        expect(() =>
            analyzeFrame(ppm(2, 2, () => [0, 0, 0], 'P6\n2 2\n65535\n'))
        ).toThrow(/maxval/)
    })
})

describe('frameResult', () => {
    const analysis = {
        width: 1024,
        height: 768,
        uniformFraction: 0.9999,
        dominantColor: '#3c3c3c',
    }

    test('a uniform console fails when the suite treats it as fatal', () => {
        const result = frameResult('post-logon', analysis, 0.999, 'fail')
        expect(result.status).toBe('fail')
        expect(result.detail).toContain('#3c3c3c')
    })

    test('the same frame only warns when the suite says advisory', () => {
        expect(frameResult('post-reboot', analysis, 0.999, 'warn').status).toBe(
            'warn'
        )
    })

    test('a painted desktop passes', () => {
        const painted = { ...analysis, uniformFraction: 0.62 }
        expect(frameResult('post-logon', painted, 0.999, 'fail').status).toBe(
            'pass'
        )
    })
})

describe('captureFrameScript', () => {
    test('is valid shell and cleans up after itself', () => {
        const script = captureFrameScript(
            9501,
            '/var/lib/vz/dump/cf-verify',
            'post-logon'
        )
        const result = spawnSync('bash', ['-n'], {
            input: script,
            encoding: 'utf8',
        })
        expect(result.status, result.stderr).toBe(0)
        expect(script).toContain('qm monitor 9501')
        expect(script).toContain('screendump')
        // A missing frame must not look like a failed capture command.
        expect(script).toContain('CF_NO_FRAME')
    })

    test('wakes the display before capturing, and does so with a bare modifier', () => {
        // Measured on a live VM: a blanked console gzipped to 3 KB and read as
        // 100% uniform — indistinguishable from a desktop that never painted.
        // The same console after this keypress gzipped to 816 KB and 4.9%.
        const script = captureFrameScript(9501, '/tmp/cf', 'post-logon')
        expect(script).toContain('sendkey shift')
        expect(script.indexOf('sendkey')).toBeLessThan(
            script.indexOf('screendump')
        )
        // Anything that types a character could dismiss a dialog or fire a
        // shortcut in the guest being tested.
        expect(script).not.toMatch(/sendkey (?!shift)/)
    })
})
