name: Build template

on:
  workflow_call:
    inputs:
      recipe:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      recipe:
        required: true
        type: string
        description: "Recipe name (e.g. debian-12)"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-one.yml
    with:
      recipe: ${{ inputs.recipe }}
    secrets: inherit

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  prune-node:
    needs: build
    if: always()
    uses: ./.github/workflows/prune-node.yml
    secrets: inherit
